### PR TITLE
Fix CloudStorage delete RuntimeException message.

### PR DESCRIPTION
**Pull request by danada**
Turned out to be a red herring :yum:

### CODE REVIEW

**Comment by chokoswitch** [comment]
Thanks! By the way, red herring for?

**Comment by danada** [comment]
I was getting errors while deleting files but was using `getUnchecked` so the error was a bit cryptic. In the same method I am composing files, so I thought it was failing at the composition step when it was in fact failing during deletion.

**Comment by chokoswitch** [comment]
Ouch - sorry for the trouble!

**Comment by danada** [comment]
It's totally my fault for being lazy and not resolving futures properly. I'm just testing some things so I didn't get stuck for very long :smiley:

**Pull request merged**
