### PR TITLE
Have gRPC postinstall only compile source files, not node_modules.

### PR DESCRIPTION
**Pull request by skywhale**
Otherwise I'm not able to install some modules e.g. @types/material-ui.

### CODE REVIEW

**Comment by curioswitch-role** [comment]
Build succeded. If you have approval, you're ready to merge!

Logs:
https://console.cloud.google.com/gcr/builds/e3971a32-0cf6-4833-b61c-0527f8cdcb91?project=curioswitch-cluster

**Comment by curioswitch-role** [comment]
Build succeded. If you have approval, you're ready to merge!

Logs:
https://console.cloud.google.com/gcr/builds/56720ece-a7bf-4a27-8e6c-cd8843b9cc04?project=curioswitch-cluster

**Comment by chokoswitch** [comment]
You're right in that the problem is that tsc is compiling much more than it should. The correct fix is to set the includes to `"./**/*"` instead of the current `"**/*"` (probably also good practice to exclude node_modules). Can add the real fix by tomorrow unless you have a chance to update this PR.

**Comment by curioswitch-role** [comment]
Build succeded. If you have approval, you're ready to merge!

Logs:
https://console.cloud.google.com/gcr/builds/288bc206-3c05-4c52-8655-08d170b4983a?project=curioswitch-cluster

**Pull request merged**
